# Generated by Django 4.2.28 on 2026-02-26 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('label', models.CharField(max_length=80)),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='floor_maps/')),
                ('map_width_px', models.IntegerField(default=1000)),
                ('map_height_px', models.IntegerField(default=700)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=200)),
                ('loc_type', models.CharField(choices=[('entrance', 'Entrance / Exit'), ('shop', 'Shop / Store'), ('restaurant', 'Restaurant / Food'), ('restroom', 'Restroom'), ('lift', 'Lift / Elevator'), ('escalator', 'Escalator'), ('stairs', 'Stairs'), ('atm', 'ATM'), ('parking', 'Parking'), ('info', 'Information Desk'), ('emergency', 'Emergency Exit'), ('junction', 'Corridor / Junction')], default='shop', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('x_pct', models.FloatField(default=50)),
                ('y_pct', models.FloatField(default=50)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='navigation.floor')),
            ],
            options={
                'ordering': ['floor__number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('total_floors', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='navigation.location')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='NavSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('found', models.BooleanField(default=True)),
                ('steps', models.IntegerField(default=0)),
                ('from_loc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_from', to='navigation.location')),
                ('mall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='navigation.mall')),
                ('to_loc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_to', to='navigation.location')),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='mall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='navigation.mall'),
        ),
        migrations.AddField(
            model_name='floor',
            name='mall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='navigation.mall'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('mall', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('mall', 'number')},
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walk_type', models.CharField(choices=[('walk', 'Walk'), ('lift', 'Lift'), ('escalator', 'Escalator'), ('stairs', 'Stairs')], default='walk', max_length=20)),
                ('weight', models.FloatField(default=1.0)),
                ('from_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='navigation.location')),
                ('mall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='navigation.mall')),
                ('to_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='navigation.location')),
            ],
            options={
                'unique_together': {('from_loc', 'to_loc')},
            },
        ),
    ]
