# Generated by Django 4.2.28 on 2026-03-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_location_area_polygon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='area_polygon',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
